FROM sbtscala/scala-sbt:eclipse-temurin-17.0.4_1.7.1_3.2.0

ENV CACHE=/var/cache/coursier

COPY project /app/project
COPY src /app/src
COPY build.sbt /app/

WORKDIR /app

RUN echo $CACHE

RUN --mount=type=cache,target=$CACHE \
 sbt -Dsbt.coursier.home=$CACHE update assembly -verbose -debug
