FROM sbtscala/scala-sbt:eclipse-temurin-17.0.4_1.7.1_3.2.0

ENV COURSIER_CACHE=/var/cache/coursier

COPY project /app/project
COPY src /app/src
COPY build.sbt /app/

WORKDIR /app

RUN echo $COURSIER_CACHE

RUN --mount=type=cache,target=$COURSIER_CACHE \
 sbt -Dsbt.coursier.home=$COURSIER_CACHE update assembly -verbose -debug
